### ISSUE TITLE
下载模型文件后运行报错，希望作者看到后能帮处理一下。谢谢

### ISSUE THREAD

**Issue by xcltapestry** [hpc203/virtual_try_on_use_deep_learning#5]
首先从项目描述上看，作者能力应当很强，项目功能也很吸引人，所以尝试执行。

但下载模型后运行时，发现会报下列错误：

[ERROR:0@1.605] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/dnn/src/dnn.cpp (3875) getLayerShapesRecursively OPENCV/DNN: [Permute]:(Mean/nhwc): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=0
[ERROR:0@1.605] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/dnn/src/dnn.cpp (3878) getLayerShapesRecursively     input[0] = [ 1 2 20 384 384 ]
[ERROR:0@1.605] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/dnn/src/dnn.cpp (3888) getLayerShapesRecursively Exception message: OpenCV(4.5.5) /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/dnn/src/layers/permute_layer.cpp:140: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'getMemoryShapes'

定位到 报错 出现在human_parsing.py文件的run_net()下
net.forward()这句。
猜测问题可能出在 lip_jppnet_384.pb 上，路径用的是绝对路径？

因为对onnx这些完全不熟悉，只能希望作者看到后，有空处理一下。

谢谢。

**Comment by lxysndy** [comment]
你好，解决了吗，盼回复

**Comment by xcltapestry** [comment]
> 
没有...

**Comment by xcltapestry** [comment]
算了，放弃了，关闭掉它。
